import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import styled from '@emotion/styled'
import { useRouter } from 'next/router'
import { ScrollMenu, VisibilityContext } from "react-horizontal-scrolling-menu";
import { Card } from 'react-bootstrap';
export default function Home() {

  const H1 = styled.h1`color: BLue;`
 // const Par = styled.p`color: Blue;`

  const My = styled.li`color: turquoise;`

  const [pokemon, setPokemon] = useState([]);
  const [pokemonpic, setPokemonpic] = useState([]);
  const [pokemon1, setPokemon1] = useState([]);
  const [selectedpokemon, setPokemn] = useState([]);
  const [query, setQuery] = useState([]);

  
const fetchPokemon=()=>{

  //fetch('https://pokeapi.co/api/v2/pokemon?limit=20')
  //.then(response => response.json())
  //.then(data => {
    //console.log(data.results)
    //setPokemon(data.results.map(p => p.name))
  //});
  fetch('https://pokeapi.co/api/v2/pokemon?offset=20&limit=20')
    .then(response=>response.json())
    .then(data=>{
      createPokemonObject(data.results)
    console.log(data.results)}).catch((err)=>{<h1>Something went wrong</h1>})

function createPokemonObject(result){

  result.forEach((pokemn) => {
  fetch(`https://pokeapi.co/api/v2/pokemon/${pokemn.name}`)
  .then(response=>response.json())
  .then(data=>{setPokemon(currenList=>[...currenList,data])}).catch((err)=>{<h1>Something went wrong</h1>}) 
  });
}

console.log(pokemon)
}


useEffect( ()=>
{
  fetchPokemon();
},[])


const router = useRouter()


  const goTo = e => {
    e.preventDefault()
    router.push({pathname: '/mypokemon',
    })
  }




  
const searchPokemon = (e) =>
{
  e.preventDefault();
  
  alert("Searching " + query);
  
  fetch( `https://pokeapi.co/api/v2/pokemon/${query}`)
  .then(response => response.json())
  .then(data => {
    console.log(data.results)
    setPokemon1(data)
  }).catch((err)=>
  {
    alert("No such pokemon exist");
  })

  
}

const myChangeHandler = (e) =>
{
  
  setQuery (e.currentTarget.value)
}


  return (

 <div className={styles.container}>



    <Head>
        <title>Create Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
     
     <header className="d-flex bg-red  justify-content-center p-2">
   
   <h1 className="md-12 text-center text-4xl md:text-5xl text-success">Lets Play with Pokemon</h1> 
    
 </header>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      </link>


      <div id="search-box" className="container-fluid bg-primary ">
          <div className="row">

              <div className="col-2 md:col-3  text-center p-1">
                <img src="\pkmn.png" className="img-fluid" style={{color: "red"}}>
                </img>
              </div>
            
            <div className="col-md-6 col-7">
              
              <form className="d-flex justify-content-center align-items-center h-auto w-100"  onSubmit= {searchPokemon } >
								
               
									<input id="search_name" type="text" name="searchelemet"  placeholder="Enter Pokemon Name" onChange={ myChangeHandler } value = {query} ></input>

                  <button type="button" className="btn btn-primary" onClick={searchPokemon}>
                 <i className="fa fa-search"></i>
                 </button>
								
                <div className="col-1 p-2">
                  <button type="button" className="btn btn-rounded btn-success"  onClick={goTo}>
                  <i className="fa fa-th-list" aria-hidden="true" ></i></button>

                </div>
              </form>
                 
            
            </div>
  
          </div>
         
      </div>


<div>
<div className=" justify-content-center align-items-center max-w-lg sm:bg-red-300 lg:max-w-md p-2 ">
<ScrollMenu >
  {pokemon.map((p)=>
  
  <Card className="main bg1  text-center text-xl md:text-sm  xs:wd-49 xs:text-3xl xs:container-fluid " key= {p} >
    
    
      <img src={p.sprites.other.dream_world.front_default} alt ={p.name} height="100" width="100"/>
      <small>{p.types[0].type.name}</small> 
      <h4>{p.name}</h4>
  
      </Card>
      
     
  )}
   </ScrollMenu>
 
  </div>
  </div>
  
  <div className="row d-flex  justify-content-center"> 
  <div className="col-sm-3">

  {pokemon1?.sprites && (


      <div className="flip-box">
      <div className="flip-box-inner">
      <div className="flip-box-front">
            <small className="text-cyan">I can Flip</small>
            <img src={pokemon1.sprites.front_default} alt="Pokemon" style={{width: "200px"},{height:"200px"}}/>
      </div>
      <div className="flip-box-back">
            <H1> Name : {pokemon1.name}</H1>
              <My>
                    {pokemon1?.types?.length > 0  && 
                    pokemon1.types.map((t) => <h6 key= {t}>Type : {t.type.name}</h6>)}
 
               </My> 
      </div>
      </div>
      </div>
)}
 </div> 
    </div>
    </div>
  )
}


